version: '3.8'
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PSWD}
            POSTGRES_DB: ${PG_DB}
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
    api:
        build:
            dockerfile: Dockerfile.local
            context: .
        container_name: api
        image: api
        env_file: .env
        network_mode: "host"
        volumes:
            - ./:/app
        depends_on:
            - postgres
volumes:
    postgres:
